feat: Laravel construct
pahud/cdk-fargate-patterns pull request #52
Opened 2021-07-08 16:34 UTC by pahud

1. Introduce the `Laravel` high-level construct with samples.
2. Refactor `WordPress`.  Move the database class to the `common` directory.

Fixes #42

2021-07-08 16:36 UTC, pahud commented
@dwchiang @neilkuan  please take a look.

2021-07-08 16:40 UTC, pahud commented on src/laravel.ts
> +    });
Hi @dwchiang 

Do we need EFS mount for the Laravel environment? If not, I am happy to remove it.

2021-07-08 16:51 UTC, neilkuan requested changes

2021-07-08 16:51 UTC, neilkuan commented on src/common/db.ts
> +      defaultDatabaseName: 'Laravel',
I think here can not hard code database name ?!

2021-07-08 16:51 UTC, neilkuan commented on src/common/db.ts
> +      defaultDatabaseName: 'Laravel',
Here also.

2021-07-08 16:59 UTC, pahud commented on src/common/db.ts
> +      defaultDatabaseName: 'Laravel',
yes we should allow user to set the default database name if any. I'll revise it tomorrow.

2021-07-09 00:15 UTC, pahud commented
@neilkuan please check it out again.

2021-07-09 01:47 UTC, neilkuan requested changes

2021-07-09 01:47 UTC, neilkuan commented on src/laravel.ts
> +    const filesystem = new efs.FileSystem(this, 'FileSystem', {
Does efs need to be kept after destroy stack?!

2021-07-09 01:47 UTC, neilkuan commented on src/common/db.ts
> +    });
```suggestion
    const dbInstance = new rds.DatabaseInstance(this, 'DBInstance', {
      vpc: props.vpc,
      vpcSubnets: props.databaseSubnets,
      databaseName: props.defaultDatabaseName,
      engine: props.instanceEngine ?? rds.DatabaseInstanceEngine.mysql({
        version: rds.MysqlEngineVersion.VER_8_0_23,
      }),
      storageEncrypted: true,
      backupRetention: props.backupRetention ?? cdk.Duration.days(7),
      credentials: rds.Credentials.fromGeneratedSecret('admin'),
      instanceType: props.instanceType ?? new ec2.InstanceType('r5.large'),
      parameterGroup: rds.ParameterGroup.fromParameterGroupName(this, 'ParameterGroup', 'default.mysql8.0'),
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });
```

2021-07-09 01:47 UTC, neilkuan commented on src/common/db.ts
> +    });
I think DatabaseInstance need this `databaseName: props.defaultDatabaseName` for single DB Instance.

2021-07-09 02:03 UTC, pahud commented on src/laravel.ts
> +    const filesystem = new efs.FileSystem(this, 'FileSystem', {
Interesting. We probably should destroy by default while leave the option for user to opt out.

2021-07-09 02:10 UTC, dwchiang commented on src/laravel.ts
> +    });
I think EFS is a good one, but not mandatory. Let's put it as an optional on/off parameter?

- Some (or most) legacy PHP application which usually does not store files in object-base storage (e.g. S3), they need EFS for smooth migration. e.g. WordPress (https://aws.amazon.com/blogs/storage/optimizing-wordpress-performance-with-amazon-efs/)
- Modern PHP applications may start to consider with object-base storage solution, they may only use the temp folder for file uploading usage. All the other file level access should move to work with object-base storage. :)

2021-07-09 02:19 UTC, pahud commented on src/laravel.ts
> +    }
Now I made the efs optional.

If `props.efsFileSystem` is provided, we provision a efs filesystem for it. In this case, which mount point should we mount to? I tentatively mount to `/efsmount` now.

@dwchiang  wdyt?

2021-07-09 02:19 UTC, pahud commented on src/laravel.ts
> +    }
cc @neilkuan

2021-07-09 02:20 UTC, pahud commented on src/integ.laravel.ts
> +    removalPolicy: cdk.RemovalPolicy.DESTROY,
Hey @neilkuan how about this?

2021-07-09 03:26 UTC, neilkuan commented on src/integ.laravel.ts
> +    removalPolicy: cdk.RemovalPolicy.DESTROY,
LGTM

2021-07-09 03:30 UTC, neilkuan approved these changes
LGTM

2021-07-09 03:37 UTC, merged