feat(nginx-php): make nginx-php service as an internal API endpoint
pahud/cdk-fargate-patterns pull request #66
Opened 2021-07-13 12:18 UTC by dwchiang

for orderService.

Also updated docker-compose :)

Fixes #40

2021-07-14 01:22 UTC, neilkuan commented
Hi @dwchiang,  please update snapshot and push again. 👍

2021-07-14 02:07 UTC, neilkuan requested changes

2021-07-14 02:07 UTC, neilkuan commented on services/golang/OrderService/main.go
> +		// go HttpGet(CUSTOMER_SVC_URL, ch)
```suggestion
		// go HttpGet(WAREHOUSE_SVC_URL, ch)
```

2021-07-14 02:10 UTC, neilkuan approved these changes

2021-07-14 02:14 UTC, neilkuan approved these changes

2021-07-14 02:17 UTC, merged

2021-07-24 06:27 UTC, pahud commented
@all-contributors please add @dwchiang  for ideas, tests and code