feat(dual-alb-fargate): dual-alb-fargate support grcp application
pahud/cdk-fargate-patterns pull request #79
Opened 2021-07-19 14:04 UTC by neilkuan

feat(dual-alb-fargate): dual-alb-fargate support grcp application
docs(readme): add grcp example code

close #69

2021-07-19 23:51 UTC, pahud requested changes
Let's create a tiny sample for gRPC maybe with golang? The python sample is way too big.

2021-07-19 23:51 UTC, pahud commented on services/python-grcp/Dockerfile
> +FROM python:3.7
please rename `python-grcp` to `python-grpc`

2021-07-19 23:51 UTC, pahud commented on src/dual-alb-fargate-svc.ts
> +          protocolVersion: t.enablegRPC ? elbv2.ApplicationProtocolVersion.GRPC : undefined,
Maybe we should expose the `protocolVersion` to the surface and allow users to specify. wdyt?

2021-07-19 23:51 UTC, pahud commented on src/integ.default.ts
> +      external: cert ? { port: 443, certificate: [cert!] } : { port: 80 },
`[cert]` should be enough given it's a conditional assignment. Is there any error without `!`?

2021-07-20 04:19 UTC, pahud requested changes
some minor suggested changes

2021-07-20 04:19 UTC, pahud commented on test/default.test.ts
> +  task.addContainer('python-grcp', {
```suggestion
  task.addContainer('go-grpc', {
```

2021-07-20 04:19 UTC, pahud commented on test/default.test.ts
> +  const task = new ecs.FargateTaskDefinition(stack, 'pythongrcpTask', {
```suggestion
  const task = new ecs.FargateTaskDefinition(stack, 'grpcTask', {
```

2021-07-20 04:19 UTC, pahud commented on test/default.test.ts
> +  // We should have two NLBs
```suggestion
  // We should have two ALBs
```

2021-07-20 04:24 UTC, pahud requested changes
please rename all `grcp` to `grpc`

2021-07-20 04:24 UTC, pahud commented on README.md
> +    // you need to specify acm and grcp port.
```suggestion
    // you need to specify acm and grpc port.
```

2021-07-20 04:24 UTC, pahud commented on src/integ.default.ts
> +// go-grcp
```suggestion
// go-grpc
```

2021-07-20 04:24 UTC, pahud commented on test/default.test.ts
> +test('DualAlbFargateService - Support gRCP application', () => {
```suggestion
test('DualAlbFargateService - Support gRPC application', () => {
```

2021-07-20 04:32 UTC, neilkuan commented on src/integ.default.ts
> +// go-grcp
okay, my fault.

2021-07-20 04:55 UTC, pahud commented on src/dual-alb-fargate-svc.ts
> +          port: t.protocolVersion === elbv2.ApplicationProtocolVersion.GRPC ? t.external!.port! : undefined,
what will happen if 

t.protocolVersion === elbv2.ApplicationProtocolVersion.GRPC

but t.external.port is undefined?

2021-07-20 05:30 UTC, pahud requested changes

2021-07-20 05:30 UTC, pahud commented on src/dual-alb-fargate-svc.ts
> +          protocolVersion: t.protocolVersion ?? undefined,
```suggestion
          protocolVersion: t.protocolVersion,
```

2021-07-20 05:30 UTC, pahud commented on src/dual-alb-fargate-svc.ts
> +          protocolVersion: t.protocolVersion ?? undefined,
```suggestion
          protocolVersion: t.protocolVersion,
```

2021-07-20 06:53 UTC, pahud approved these changes

2021-07-20 06:59 UTC, merged

2021-07-24 06:22 UTC, pahud commented
@all-contributors please add @neilkuan  for design and code.